plugins { id("hedgefund.java-service") }
dependencies {
    implementation(project(":libs:yahoo"))
    implementation(project(":libs:worldbank"))
    implementation(project(":libs:investing"))
    implementation(project(":libs:baostock"))
    implementation(project(":libs:eastmoney"))
    implementation(project(":libs:sina"))
    implementation(project(":libs:tencent"))
    implementation(project(":libs:gmd"))
    implementation(project(":libs:bea"))
    implementation(project(":libs:bls"))
    implementation(project(":libs:eia"))
    implementation(project(":libs:fdic"))
    implementation(project(":libs:calcfi"))
    implementation(project(":libs:oecd"))
    implementation(project(":libs:imf"))
    implementation(project(":libs:sec"))
    implementation(project(":libs:treasury"))
    implementation(project(":libs:fred"))
    implementation(project(":libs:defillama"))
    implementation(project(":libs:coinbase"))
    implementation(project(":libs:binance"))
    implementation(project(":libs:cboe"))
    implementation(project(":libs:config-core"))
    implementation(project(":libs:observability"))
    implementation(libs.slf4j.api)
    implementation(libs.logback.classic)
}
application { mainClass.set("com.hedgefund.runner.Main") }
